name: documentation

on:
  push:
    branches: [develop]

jobs:
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: "Install main dependencies"
        if: ${{ !steps.main-cache-restore.outputs.cache-hit }}
        run: npm ci
      - name: "[INIT] Restore docs dependency cache"
        id: docs-cache-restore
        uses: actions/cache@v2
        with:
          path: docs/node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-docs${{ hashFiles('**/package-lock.json') }}
      - name: "Install docs dependencies"
        if: ${{ !steps.docs-cache-restore.outputs.cache-hit }}
        run: npm ci
        working-directory: ./docs
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGE_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: kaihodev
        run: |
          git config --global user.name 'kaihodev'
          git config --global user.email kaihodev@gmail.com
          npm run deploy
        working-directory: ./docs
